#!/bin/bash

rm /run/media/gedweb/SKR_PRO/*
pio run -e BIGTREE_SKR_PRO $@ \
&& cp /home/gedweb/Develop/Marlin/.pio/build/BIGTREE_SKR_PRO/firmware.bin /run/media/gedweb/SKR_PRO/ \
&& sync \
&& echo DONE!
